/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package falsissimo;

import java.io.IOException;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pazzagli.angelica
 */
public class GameForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameForm.class.getName());
    private GameManager gameManager;
    private boolean giocoFinito = false;
    /**
     * Creates new form GameForm
     * @param gm
     */
    public GameForm(GameManager gm) {
        initComponents();
        this.gameManager = gm;
        lblNickname.setText(gm.getNickname() + " " + gm.giocatore.nome);
        valueLabel();
        insertImage();
        txtEventi.setLineWrap(true);
        txtEventi.setWrapStyleWord(true);
        barPercorso.setValue(gameManager.getProgresso());
    }
    
    public void insertImage() {
        int image = gameManager.getPersonaggio();
        switch (image) {
            case 1:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GamePaparazzo.png")));
                break;
            case 2:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GameCarcerato.png")));
                break;
            default:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GameModello.png")));
                break;
        }
    }
    
    public void valueLabel() {
        lblSoldi.setText("" + gameManager.giocatore.getSoldi());
        lblFama.setText(gameManager.giocatore.getFama() + "/10");
        lblAstuzia.setText(gameManager.giocatore.getAstuzia() + "/10");
    }
    
    private boolean gameOver(String messaggio) {
        if(gameManager.giocatore.getSoldi() <= 0) {
            return true;
        }
        if(messaggio.contains("GAME OVER")) {
            return true;
        }
        return false;
    }
    
    private void fineGioco(String messaggio) {
        txtEventi.append("\n" + messaggio);
        javax.swing.JOptionPane.showMessageDialog(this, "GAME OVER\n" + messaggio);
        this.dispose();
    }
    
    private void checkProgress() throws IOException {
        if(giocoFinito) {
            return;
        }
        if (barPercorso.getValue() >= 100) {
            giocoFinito = true;
            gameManager.writeClassifica(gameManager.getPunti());
            javax.swing.JOptionPane.showMessageDialog(this, "COMPLIMENTI HAI COMPLETATO IL GIOCO!\nClassifica aggiornata.");
            this.dispose();
        }
    }
    
    private void aumentaBar(int incremento) throws IOException {
        int nuovoValore = gameManager.getProgresso() + incremento;
        if (nuovoValore > barPercorso.getMaximum()) {
            nuovoValore = barPercorso.getMaximum();
        }
        if (nuovoValore < 0) {
            nuovoValore = 0;
        }
        barPercorso.setValue(nuovoValore);
        gameManager.setProgresso(nuovoValore);
        checkProgress();
    }
    
    private void controlloAumento(String messaggio) {
        if(messaggio.contains("+")) {
            try {
                aumentaBar(new Random().nextInt(15, 31));
            } catch (IOException ex) {
                System.getLogger(GameForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        } else if(messaggio.contains("-")) {
            try {
                aumentaBar(-(new Random().nextInt(1, 6)));
            } catch (IOException ex) {
                System.getLogger(GameForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPersonaggio = new javax.swing.JLabel();
        lblTitolo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNickname = new javax.swing.JLabel();
        lblTitSoldi = new javax.swing.JLabel();
        lblTitFama = new javax.swing.JLabel();
        lblTitAstuzia = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        lblSoldi = new javax.swing.JLabel();
        lblFama = new javax.swing.JLabel();
        lblAstuzia = new javax.swing.JLabel();
        pnlEventi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEventi = new javax.swing.JTextArea();
        lblOspite = new javax.swing.JLabel();
        btnAbilità = new javax.swing.JButton();
        btnEsplora = new javax.swing.JButton();
        barPercorso = new javax.swing.JProgressBar();
        lblCorona = new javax.swing.JLabel();
        btnUsaSoldi = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblPersonaggio.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblPersonaggio.setForeground(new java.awt.Color(255, 255, 255));

        lblTitolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header.png"))); // NOI18N

        lblNickname.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(255, 255, 255));
        lblNickname.setText("lblNickname");

        lblTitSoldi.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitSoldi.setForeground(new java.awt.Color(255, 255, 255));
        lblTitSoldi.setText("SOLDI:");

        lblTitFama.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitFama.setForeground(new java.awt.Color(255, 255, 255));
        lblTitFama.setText("FAMA:");

        lblTitAstuzia.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitAstuzia.setForeground(new java.awt.Color(255, 255, 255));
        lblTitAstuzia.setText("ASTUZIA:");

        btnSalva.setBackground(new java.awt.Color(204, 204, 204));
        btnSalva.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnSalva.setText("SAVE GAME");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        lblSoldi.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblSoldi.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldi.setText("0");

        lblFama.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblFama.setForeground(new java.awt.Color(255, 255, 255));
        lblFama.setText("0");

        lblAstuzia.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblAstuzia.setForeground(new java.awt.Color(255, 255, 255));
        lblAstuzia.setText("0");

        txtEventi.setColumns(20);
        txtEventi.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        txtEventi.setRows(5);
        txtEventi.setText("EVENTI");
        jScrollPane1.setViewportView(txtEventi);

        javax.swing.GroupLayout pnlEventiLayout = new javax.swing.GroupLayout(pnlEventi);
        pnlEventi.setLayout(pnlEventiLayout);
        pnlEventiLayout.setHorizontalGroup(
            pnlEventiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEventiLayout.setVerticalGroup(
            pnlEventiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAbilità.setBackground(new java.awt.Color(204, 204, 204));
        btnAbilità.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnAbilità.setText("USA ABILITA'");
        btnAbilità.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbilitàActionPerformed(evt);
            }
        });

        btnEsplora.setBackground(new java.awt.Color(204, 204, 204));
        btnEsplora.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnEsplora.setText("ESPLORA");
        btnEsplora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsploraActionPerformed(evt);
            }
        });

        barPercorso.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        barPercorso.setForeground(new java.awt.Color(255, 0, 255));
        barPercorso.setStringPainted(true);

        lblCorona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FinaleCorona.png"))); // NOI18N

        btnUsaSoldi.setBackground(new java.awt.Color(204, 204, 204));
        btnUsaSoldi.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnUsaSoldi.setText("USA SOLDI");
        btnUsaSoldi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsaSoldiActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(204, 204, 204));
        btnInfo.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnInfo.setText("i");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTitFama)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblFama, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEsplora, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblTitSoldi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblTitAstuzia)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAbilità, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnUsaSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInfo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOspite, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlEventi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(barPercorso, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCorona)
                        .addGap(146, 146, 146))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitolo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPercorso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorona, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlEventi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOspite, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAbilità, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUsaSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEsplora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPersonaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNickname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTitSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTitFama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        try {
            gameManager.salvaPartita();
        } catch (IOException ex) {
            System.getLogger(GameForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnAbilitàActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbilitàActionPerformed
        String messaggio = gameManager.usaAbilità();
        valueLabel();
        if(gameOver(messaggio)) {
            fineGioco(messaggio);
            return;
        }
        lblOspite.setIcon(new ImageIcon(getClass().getResource("/images/Stella.png")));
        controlloAumento(messaggio);
        txtEventi.append("\n" + messaggio);
        btnAbilità.setEnabled(false);
    }//GEN-LAST:event_btnAbilitàActionPerformed

    private void btnEsploraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsploraActionPerformed
        Evento evento = gameManager.esplora();
        String messaggio = evento.getMessaggio();
        valueLabel();
        lblOspite.setIcon(new ImageIcon(getClass().getResource(evento.getImmagine())));
        controlloAumento(messaggio);
        txtEventi.append("\n" + messaggio);
        if(gameManager.giocatore.getSoldi() == 0) {
            messaggio = "Soldi terminati";
        }
        if(gameOver(messaggio)) {
            fineGioco(messaggio);
            return;
        }
    }//GEN-LAST:event_btnEsploraActionPerformed

    private void btnUsaSoldiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsaSoldiActionPerformed
        if(gameManager.giocatore.getSoldi() < 150000) {
            txtEventi.append("\nNon hai abbastanza soldi!");
            return;
        }
        gameManager.usaSoldi();
        valueLabel();
        lblOspite.setIcon(new ImageIcon(getClass().getResource("/images/Portafoglio.png")));
        txtEventi.append("\nHai speso 150.000 euro.");
        try {
            aumentaBar(new Random().nextInt(20, 31));
        } catch (IOException ex) {
            System.getLogger(GameForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnUsaSoldiActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        String info = "INFO GIOCO\n\n"
        + "La barra con sotto la corona rappresenta il tuo percorso per diventare una star internazionale: "
        + "più avanzi, più sei vicino al successo.\n\n"
        + "- USA SOLDI: ti fa avanzare di una percentuale casuale tra il 20% e il 30%, \nma costa 150.000€. Usalo con attenzione: i soldi influiscono negli eventi casuali.\n\n"
        + "- ESPLORA: genera un evento casuale che può essere un bonus o un malus e influenzare le tue statistiche o il progresso.\n\n"
        + "- USA ABILITA': attiva l’abilità speciale del personaggio scelto, aumentando soldi, fama o astuzia \ne facendoti avanzare nel percorso. Utilizzabile una sola volta.\n\n"
        + "- SAVE GAME: salva la partita per permetterti di riprendere dal punto in cui hai lasciato.\n\n"
        + "Gestisci bene le risorse e le scelte: ogni decisione può portarti al successo o al GAME OVER.\n\n"
        + "BUONA FORTUNA!";
        
        JOptionPane.showMessageDialog(this, info);
    }//GEN-LAST:event_btnInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barPercorso;
    private javax.swing.JButton btnAbilità;
    private javax.swing.JButton btnEsplora;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSalva;
    private javax.swing.JButton btnUsaSoldi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAstuzia;
    private javax.swing.JLabel lblCorona;
    private javax.swing.JLabel lblFama;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblOspite;
    private javax.swing.JLabel lblPersonaggio;
    private javax.swing.JLabel lblSoldi;
    private javax.swing.JLabel lblTitAstuzia;
    private javax.swing.JLabel lblTitFama;
    private javax.swing.JLabel lblTitSoldi;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlEventi;
    private javax.swing.JTextArea txtEventi;
    // End of variables declaration//GEN-END:variables
}
