/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package falsissimo;

import javax.swing.ImageIcon;

/**
 *
 * @author pazzagli.angelica
 */
public class GameForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameForm.class.getName());
    private GameManager gameManager;
    /**
     * Creates new form GameForm
     * @param gm
     */
    public GameForm(GameManager gm) {
        initComponents();
        this.gameManager = gm;
        lblNickname.setText(gm.getNickname() + " " + gm.giocatore.nome);
        insertImage();
    }
    
    public void insertImage() {
        int image = gameManager.getPersonaggio();
        switch (image) {
            case 1:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GamePaparazzo.png")));
                break;
            case 2:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GameCarcerato.png")));
                break;
            default:
                lblPersonaggio.setIcon(new ImageIcon(getClass().getResource("/images/GameModello.png")));
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPersonaggio = new javax.swing.JLabel();
        lblTitolo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNickname = new javax.swing.JLabel();
        lblTitSoldi = new javax.swing.JLabel();
        lblTitFama = new javax.swing.JLabel();
        lblTitAstuzia = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        lblSoldi = new javax.swing.JLabel();
        lblFama = new javax.swing.JLabel();
        lblAstuzia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblPersonaggio.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblPersonaggio.setForeground(new java.awt.Color(255, 255, 255));

        lblTitolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header.png"))); // NOI18N

        lblNickname.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(255, 255, 255));
        lblNickname.setText("lblNickname");

        lblTitSoldi.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitSoldi.setForeground(new java.awt.Color(255, 255, 255));
        lblTitSoldi.setText("SOLDI:");

        lblTitFama.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitFama.setForeground(new java.awt.Color(255, 255, 255));
        lblTitFama.setText("FAMA:");

        lblTitAstuzia.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblTitAstuzia.setForeground(new java.awt.Color(255, 255, 255));
        lblTitAstuzia.setText("ASTUZIA:");

        btnSalva.setBackground(new java.awt.Color(204, 204, 204));
        btnSalva.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnSalva.setText("SAVE GAME");

        lblSoldi.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblSoldi.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldi.setText("0");

        lblFama.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblFama.setForeground(new java.awt.Color(255, 255, 255));
        lblFama.setText("0");

        lblAstuzia.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lblAstuzia.setForeground(new java.awt.Color(255, 255, 255));
        lblAstuzia.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTitSoldi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitFama)
                        .addGap(18, 18, 18)
                        .addComponent(lblFama, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitAstuzia)
                        .addGap(18, 18, 18)
                        .addComponent(lblAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitFama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAstuzia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAstuzia;
    private javax.swing.JLabel lblFama;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPersonaggio;
    private javax.swing.JLabel lblSoldi;
    private javax.swing.JLabel lblTitAstuzia;
    private javax.swing.JLabel lblTitFama;
    private javax.swing.JLabel lblTitSoldi;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
