/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package falsissimo;

/**
 *
 * @author pazzagli.angelica
 */
public class MenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuForm.class.getName());
    private GameManager gameManager;
    private int personaggioScelto = 0;
    /**
     * Creates new form MenuForm
     */
    public MenuForm(GameManager gm) {
        initComponents();
        
        btnProsegui.setEnabled(false);
        this.gameManager = gm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        btnCarcerato = new javax.swing.JButton();
        btnModello = new javax.swing.JButton();
        btnPaparazzo = new javax.swing.JButton();
        btnProsegui = new javax.swing.JButton();
        lblFalsissimo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCarcerato = new javax.swing.JLabel();
        lblPaparazzo = new javax.swing.JLabel();
        lblModello = new javax.swing.JLabel();
        lblDescrizioneMod = new javax.swing.JLabel();
        lblDescrizioneMod1 = new javax.swing.JLabel();
        lblDescrizioneMod2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblTitolo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setText("Scegli il tuo personaggio");

        btnCarcerato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CoronaCarcerato.png"))); // NOI18N
        btnCarcerato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarceratoActionPerformed(evt);
            }
        });

        btnModello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CoronaModello.png"))); // NOI18N
        btnModello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelloActionPerformed(evt);
            }
        });

        btnPaparazzo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CoronaPaparazzo.png"))); // NOI18N
        btnPaparazzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaparazzoActionPerformed(evt);
            }
        });

        btnProsegui.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnProsegui.setText("OK");
        btnProsegui.setToolTipText("");
        btnProsegui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProseguiActionPerformed(evt);
            }
        });

        lblFalsissimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header.png"))); // NOI18N

        lblCarcerato.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblCarcerato.setForeground(new java.awt.Color(255, 255, 255));
        lblCarcerato.setText("CARCERATO");

        lblPaparazzo.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblPaparazzo.setForeground(new java.awt.Color(255, 255, 255));
        lblPaparazzo.setText("PAPARAZZO");

        lblModello.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblModello.setForeground(new java.awt.Color(255, 255, 255));
        lblModello.setText("MODELLO");

        lblDescrizioneMod.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblDescrizioneMod.setForeground(new java.awt.Color(255, 255, 255));
        lblDescrizioneMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescrizioneMod.setText("+SOLDI");

        lblDescrizioneMod1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblDescrizioneMod1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescrizioneMod1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescrizioneMod1.setText("+ASTUZIA");

        lblDescrizioneMod2.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblDescrizioneMod2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescrizioneMod2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescrizioneMod2.setText("+FAMA");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFalsissimo, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProsegui)
                        .addGap(304, 304, 304))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lblDescrizioneMod, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDescrizioneMod2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblModello)
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnModello, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCarcerato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCarcerato, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescrizioneMod1)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPaparazzo)
                                    .addComponent(btnPaparazzo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitolo)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblFalsissimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCarcerato)
                            .addComponent(lblModello))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCarcerato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnModello, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescrizioneMod)
                            .addComponent(lblDescrizioneMod1)
                            .addComponent(lblDescrizioneMod2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnProsegui)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(lblPaparazzo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPaparazzo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProseguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProseguiActionPerformed
        gameManager.sceltaPersonaggio(personaggioScelto);
        GameForm gameForm = new GameForm(gameManager);
        gameForm.setVisible(true);
    }//GEN-LAST:event_btnProseguiActionPerformed

    private void btnModelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelloActionPerformed
        this.personaggioScelto = 3;
        btnProsegui.setEnabled(true);
    }//GEN-LAST:event_btnModelloActionPerformed

    private void btnCarceratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarceratoActionPerformed
        this.personaggioScelto = 2;
        btnProsegui.setEnabled(true);
    }//GEN-LAST:event_btnCarceratoActionPerformed

    private void btnPaparazzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaparazzoActionPerformed
        this.personaggioScelto = 1;
        btnProsegui.setEnabled(true);
    }//GEN-LAST:event_btnPaparazzoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarcerato;
    private javax.swing.JButton btnModello;
    private javax.swing.JButton btnPaparazzo;
    private javax.swing.JButton btnProsegui;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCarcerato;
    private javax.swing.JLabel lblDescrizioneMod;
    private javax.swing.JLabel lblDescrizioneMod1;
    private javax.swing.JLabel lblDescrizioneMod2;
    private javax.swing.JLabel lblFalsissimo;
    private javax.swing.JLabel lblModello;
    private javax.swing.JLabel lblPaparazzo;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
